apiVersion: v1
kind: Service
metadata:
  name: rust-api
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
  selector:
    app: rust-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rust-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rust-api
  template:
    metadata:
      labels:
        app: rust-api
    spec:
      containers:
      - name: rust-api
        image: rust-api:v1
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
        env:
          - name: PG_HOST
            value: "postgres"
          - name: PG_PASSWORD
            value: "password"
          - name: PG_USER
            value: "postgres"
          - name: PG_DBNAME
            value: "appdb"
