apiVersion: v1
kind: Service
metadata:
  name: go-web-app-service
  labels:
    app: go-web
spec:
  type: ClusterIP  # Internal service (only accessible within cluster)
  selector:
    app: go-web  # Routes traffic to Pods with this label
  ports:
  - protocol: TCP
    port: 80        # Service exposes port 80
    targetPort: 8080  # Forwards to container port 8080
    name: http
