apiVersion: v1
kind: Pod
metadata:
  name: pod-taint-test
  labels:
    app: taint-test
spec:
  containers:
  - name: nginx
    image: nginx:alpine
  # Uncomment to test toleration
  tolerations:
  - key: "env"
    operator: "Equal"
    value: "prod"
    effect: "NoSchedule"
